apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appfe-ing
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: sn7-clothing.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.nameservice }}
            port:
              number: {{ .Values.port }}
        path: /
        pathType: Prefix