apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appfe-ing
  namespace: default
spec:
  ingressClassName: haproxy
  rules:
  - host: sn7-clothing.com
    http:
      paths:
      - backend:
          service:
            name: myapp-svc
            port:
              number: 8080
        path: /
        pathType: Prefix