apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameservice }}
  namespace: b2c-newgen-fe
spec:
  selector: {{ include "common.labels" . | indent 4}}
  type: {{ .Values.typesvc }}
  ports:
    - port: {{ .Values.port }}
      targetPort: 3000
      protocol: TCP