apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: hoomee.nhatth.com
spec:
  ingressClassName: fe-ing
  rules:
  - host: hoomee.nhatth.com
    http:
      paths:
      - backend:
          service:
            name: myapp-svc
            port:
              number: 3000
        path: /
        pathType: Prefix